### ISSUE TITLE
Embedded Postgres doesn't shut down properly

### ISSUE THREAD

**Issue by sazzer** [yandex-qatools/postgresql-embedded#1]
I've used the postgresql-embedded library to run up a Postgres database for my application when running in Integration Test or Development mode. This starts up perfectly well by using the example from the Readme, but shutting down doesn't work correctly. Either by calling

    PostgresProcess.stop()

or else

    Executable.stop()

If I call PostgresProcess.stop() then I get an exception thrown, whereas if I call Executable.stop() then I don't get any exception but in both cases the postgres process is left running.

The exception that I get is:

    java.lang.NullPointerException: executable is NULL
        at de.flapdoodle.embed.process.extract.ImmutableExtractedFileSet.<init>(ImmutableExtractedFileSet.java:42)
        at de.flapdoodle.embed.process.extract.ImmutableExtractedFileSet$Builder.build(ImmutableExtractedFileSet.java:106)
        at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:84)
        at ru.yandex.qatools.embed.postgresql.ext.PostgresArtifactStore.extractFileSet(PostgresArtifactStore.java:69)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
        at ru.yandex.qatools.embed.postgresql.PostgresProcess.runCmd(PostgresProcess.java:91)
        at ru.yandex.qatools.embed.postgresql.PostgresProcess.shutdownPostgres(PostgresProcess.java:79)
        at ru.yandex.qatools.embed.postgresql.PostgresProcess.sendStopToPostgresqlInstance(PostgresProcess.java:75)
        at ru.yandex.qatools.embed.postgresql.PostgresProcess.stopInternal(PostgresProcess.java:57)

**Comment by smecsia** [comment]
@sazzer Thank you for the request. 
Which OS are you using?

**Comment by sazzer** [comment]
That helps, doesn't it?

I'm using 64 bit Linux Ubuntu 14.10, running with maven 3.2.2 and Java 8u5.

**Comment by smecsia** [comment]
Hmm. I'm actually have the same set and cannot reproduce the described problem.
By the way, you should use `stop` method of the `PostgresProcess` instance, and not of the `Executable` at all. 
It seems that the artifact store is already cleaned up when you call `stop` method of the process. This could be caused by the call to `stop` of Executable, as it cleans after itself. Please try not to use it before you call `stop` of `PostgresProcess`.

**Comment by sazzer** [comment]
I only tried the method on Executable because the other one threw the
exception. I understand that's not right but I wanted to just see if it
helped.

If it matters, this is being called from Spring, starting in an init-method
call and the actual shutdown here in a destroy-method call. I don't see
that this should make any difference though, unless there are other Java
shutdown hooks happening too.

**Comment by smecsia** [comment]
@sazzer There is a shutdown hook actually registered within the Flapdoodle's Executable implementation... But I believe it should not be called since you're stopping the process manually. 
Can you check one thing? Try to stop  service not by the `destroy-method`, but within the `tearDown` method of your test suite.

**Comment by sazzer** [comment]
I'll give it a go later, though the use of destroy-method was because I do
dev using by just running mvn cargo:run and it starts up a full tomcat with
everything ready to go. If that doesn't work then it might be vagrant
time...

**Comment by sazzer** [comment]
Yes, if I call process.stop() manually when the code is running then it shutsdown cleanly. So it looks like it's simply that the Executable Shutdown hook is firing *before* the Spring shutdown hook - which is believable, since Spring starts up the Executable in the first place, so the Spring shutdown hook will be registered first. 

I have just tried changing the Daemon Process flag to false - which in theory means that there shouldn't be a shutdown hook registered by Executable - but that doesn't seem to have helped any.

**Comment by smecsia** [comment]
@sazzer, I've just pushed the commit, which has tiny changes in cleanup behavior - it cleans the artifact store directory just after the `pg_ctl stop` command is executed successfully. Can you check if it helps?

**Comment by sazzer** [comment]
Just checked out the trunk, built it, and made my code use the new 1.2-SNAPSHOT - and it's not made any difference :(

**Comment by smecsia** [comment]
@sazzer Please check it once again. I've added tiny fixes  (3961c7d65ccf840664375cd81fce7e0c8fc7ba69) and implemented the test, which uses Spring context. 
If it helps, I will release a new version.

**Comment by sazzer** [comment]
Success :D It seems to be working fine now.  Thank you :D
