### ISSUE TITLE
Version 2.7 not available in Maven Central

### ISSUE THREAD

**Issue by tazle** [yandex-qatools/postgresql-embedded#121]
It seems that version 2.7 has been tagged, but is not available on Maven Central. Is this intentional?

2.7 is not listed on the result list of e.g. http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22ru.yandex.qatools.embed%22%20AND%20a%3A%22postgresql-embedded%22.

**Comment by julianladisch** [comment]
@smecsia Can you release 2.7 with security update #120 ? Thank you!

**Comment by smecsia** [comment]
@tazle @julianladisch sorry mates, we're experiencing little troubles with our CI system at the moment, so I can't release it right now. I'll come back to you a bit later (hopefully by the end of this week).

**Comment by smecsia** [comment]
Version 2.8 has been released
