### ISSUE TITLE
When do you plan to release version supporting 10.3 ?

### ISSUE THREAD

**Issue by fredclose** [yandex-qatools/postgresql-embedded#128]
When do you plan to release version supporting 10.3 ?

**Comment by julianladisch** [comment]
@smecsia Can you release 2.9 with security update #126 ? Thank you!

**Comment by smecsia** [comment]
@fredclose @julianladisch version 2.9 has been released.

P.S. you can always choose custom postgres version on your side.

**Comment by fredclose** [comment]
@smecsia what's the recommended way to use a custom version ? 
Implement de.flapdoodle.embed.process.distribution.IVersion ?

**Comment by julianladisch** [comment]
@fredclose Yes, unless `new EmbeddedPostgres("10.3")` is sufficient for you.
https://github.com/yandex-qatools/postgresql-embedded#how-to-use-your-custom-version-of-postgresql

**Comment by julianladisch** [comment]
@smecsia : If a PostgreSQL release is available that fixes a security issue then there should be a postgresql-embedded release that defaults to that security fix. When I want to update the PostgreSQL version in some project I want to change the pom.xml only without altering the java code.

**Comment by fredclose** [comment]
@julianladisch you can avoid changing the code by refering to the main version 

```
ru.yandex.qatools.embed.postgresql.distribution.Version.Main#V9_6
ru.yandex.qatools.embed.postgresql.distribution.Version.Main#V10
```
