### ISSUE TITLE
Passing InitDB Arguments

### ISSUE THREAD

**Issue by dev-mobile** [yandex-qatools/postgresql-embedded#14]
Hi, 
I appreciate your work a lot.

I'm trying to re-import a dump, but it fails because 'value too long for column...'.
The reason is that we have _german umlauts_ in the dumped data.
To make this work there should be a possibility to pass some arguments to the _InitDB_ process.
Like ```new String[]{"-E", "'UTF-8'", "--lc-collate='de_DE.UTF-8'", "--lc-ctype=locale='de_DE.UTF-8'"}```
Do you think it will be ever possible to pass some arguments to the InitDb process?
Something like in : https://gist.github.com/dev-mobile/9383ee242c26bafac2b5

Thank you

**Comment by smecsia** [comment]
Hi @dev-mobile, this should be made within the [InitDbProcess.java](https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/main/java/ru/yandex/qatools/embed/postgresql/InitDbProcess.java). The way to do this is to add the `additionalInitDbParams` property to [AbstractPostgresConfig.java](https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/main/java/ru/yandex/qatools/embed/postgresql/config/AbstractPostgresConfig.java) and then use it in the InitDbProcess. 
I think I could implement this a bit later (too busy right now). But feel free to send a PR if you are able to implement in on your own.

**Comment by smecsia** [comment]
Fixed in #15
