### ISSUE TITLE
Postgres 11.1 for Linux

### ISSUE THREAD

**Issue by mdoering** [yandex-qatools/postgresql-embedded#149]
The latest stable 11 branch of postgres is not supported which is a big loss.
If EnterpriseDB continues to drop support for Linux can we switch to another binary distribution? The embedded server has been really nice for us to run continuous integration tests, but that requires linux.

**Comment by Angeland** [comment]
Yup, in our project we are looking into dropping usage in exchange to running a container/pod for testing from https://hub.docker.com/_/postgres/

**Comment by mdoering** [comment]
I am removing postgresql-embedded now from my project until this is solved. No way without pg11 on linux

**Comment by smecsia** [comment]
@liias @mdoering thanks for your interest! Unfortunately I don't have enough time to maintain this project anymore. Your approach of using Test Containers as an alternative is the best bet. I strongly recommend it as the great alternative providing the best experience as I migrated to it myself (see updated Readme).

**Comment by liias** [comment]
As a note, another alternative is https://github.com/opentable/otj-pg-embedded which I will try out (I would like to start up postgres as fast as possible during code generation, so testcontainers is a bit slow for that)
