### ISSUE TITLE
Postgres 9.4.1 Binaries on OS X don't unpack

### ISSUE THREAD

**Issue by sazzer** [yandex-qatools/postgresql-embedded#2]
Using the Embedded PostgreSQL server on Linux works perfectly fine. Using it on OS X doesn't work though. I get the error:

    Caused by: java.util.NoSuchElementException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at java.util.Collections$3.nextElement(Collections.java:5275)
	at de.flapdoodle.embed.process.extract.ZipExtractor$ZipArchiveWrapper.getNextEntry(ZipExtractor.java:58)
	at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:68)
	at ru.yandex.qatools.embed.postgresql.ext.PostgresArtifactStore.extractFileSet(PostgresArtifactStore.java:69)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)

When running from Java code. However, the Zip file that was downloaded seems to be OK, and I can unpack it using both the *zip* and *jar* tools.

    $ jar -xf ../postgresql-9.4.1-1-osx-binaries.zip
    $ ls
    pgsql
    $

**Comment by sazzer** [comment]
$ mvn -version
Picked up _JAVA_OPTIONS: -Xms256m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=1024m
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 13:51:28+0000)
Maven home: /Users/coxg/java/apache-maven-3.0.5
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

**Comment by sazzer** [comment]
The problem is that on OS X, the AbstractExtractor class is assuming that Enumeration.getNextEntry() will return null when we reach the end. This ultimately ends up calling Enumeration.nextElement(), where the Enumeration is actually created by calling Collections.enumeration() wrapping a LinkedHashMap. The problem here is that the LinkedHashMap implementation seems to NPE when we reach the end of the list, instead of behaving as you'd hope.

As it turns out, if the ZipExtractor checked entries.hasMoreElements() as well then this problem wouldn't happen.

**Comment by sazzer** [comment]
As an annoyance, this is all in de.flapdoodle.embed.process-1.41.1.jar and not part of the postgresql-embedded project.

**Comment by sazzer** [comment]
Just updated to Java 8u45 and unfortunately it's made no difference

**Comment by sazzer** [comment]
I've just opened pull request https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/25 on de.flapdoodle.embed.process that appears to fix this problem.

**Comment by smecsia** [comment]
Great! Thank you. Guys from Flapdoodle-OSS should review it soon. They actually respond fairly quickly.

**Comment by harishkannarao** [comment]
Hi, I am facing the same issue in Windows 64 bit OS as well.  Fixing this issue will be highly helpful. :)

:+1:

**Comment by smecsia** [comment]
@sazzer , @harishkannarao I've just released a new version 1.3 with the newer embed.process dependency. Please, verify the problem is solved.

**Comment by harishkannarao** [comment]
Hi @smecsia , I have tested this issue in Windows 64 bit OS and it is working fine. :)

**Comment by smecsia** [comment]
It seems that this issue is resolved. I'll try to fix other windows issues this week.
