### ISSUE TITLE
postgres does not start on win7 x64

### ISSUE THREAD

**Issue by evrastil** [yandex-qatools/postgresql-embedded#28]
`Extract embedpostgresql\postgresql-9.5.0-1-windows-x64-binaries.zip DONE
10:28:46.497 [main] DEBUG d.f.e.process.runtime.ProcessControl - Detected pid: 4648
10:28:52.940 [main] INFO  d.f.embed.process.runtime.Executable - start ru.yandex.qatools.embed.postgresql.config.PostgresConfig@282003e1
10:28:52.949 [main] DEBUG d.f.e.process.runtime.ProcessControl - Detected pid: 11520
Bře 15, 2016 10:29:12 DOP. ru.yandex.qatools.embed.postgresql.PostgresProcess onAfterProcessStart
SEVERE: Failed to read PID file (File 'C:\catalog\temp\postmaster.pid' does not exist)
10:29:13.665 [main] DEBUG d.f.e.process.runtime.ProcessControl - Detected pid: 10792`

Postgres embedded service does not start on win7 x64

im using version 1.10

this is how im starting postgres

`        PostgresStarter<PostgresExecutable, PostgresProcess> runtime = PostgresStarter.getDefaultInstance();
        config = new PostgresConfig(PRODUCTION, new AbstractPostgresConfig.Net(
                "localhost", findFreePort()
        ), new AbstractPostgresConfig.Storage("test", "temp"), new AbstractPostgresConfig.Timeout(),
                new AbstractPostgresConfig.Credentials("user", "password"));
        PostgresExecutable exec = runtime.prepare(config);
        process = exec.start();`

**Comment by smecsia** [comment]
@evrastil Are you trying to launch postgres as a user with admin privileges in your system? If so, this is a duplication of #5 
Please try to launch postgres binaries manually http://www.postgresql.org/docs/9.1/static/server-start.html and share your experience.

**Comment by evrastil** [comment]
You are right Im running as system user

> C:\Users\asdf\AppData\Local\Temp\postgresql-embed-f4002ef1-55cd-48a7-9b81-91255b03b95a\pgsql\bin>postgres -D C:\Users\asdf\AppData\Loc
al\Temp\postgresql-embed-f4002ef1-55cd-48a7-9b81-91255b03b95a\db-content-e73e4c89-687a-4dfc-8316-5a5c04895e61
Execution of PostgreSQL by a user with administrative permissions is not
permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromises.  See the documentation for
more information on how to properly start the server.

This is big issue for me because I cant change my environment, did you find a workaround for this?

**Comment by smecsia** [comment]
@evrastil Unfortunately no. There is a PR #22 which probably would allow to achieve something like running postgres commands as `runas /user:postgres ...`. This might solve your issue. 
It would be greate if you could test postgresql-embedded with that patch. If it works, I'll merge it and release the new version.

**Comment by evrastil** [comment]
To add runas will not solve my problem only user I have has admin privilages and i cant add any new.

Did you consider using just pg_ctl start/stop -U test -P pwd-D datadir 
because it seems to avoid the security pg check and it would work for me, IMHO no need to user psotgres zou could just user the pg_ctl  wrapper.

btw I will check if the PR #22 works but Ill geve to ge a hold of another computer where I can change things.

**Comment by smecsia** [comment]
@evrastil This won't work. We have to use `initdb` anyway, because we need to initialize new database first. Have you tried launching it under your user?

**Comment by evrastil** [comment]
@smecsia  yes I did and I can confirm it works. **BUT** it is still not usable for me in corporate environment where I must use win7 and other people must use it. I have only one win user which I can not change or add another which would not have admin role :(.

`initdb` runs fine there is no issues with that under and if tere would be a way and Im sure there is to `pg_ctl start` postgres it would solve the problem for all win users. I think actualy most of win users are in admin group for convinience. I could try to modify your code so it would be able to start the postgres using the `pg_ctl` wrapper. It would be nice if `ru.yandex.qatools.embed.postgresql.PostgresStarter#getDefaultInstance` could take IRuntimeConfig param which would modify it to start the postgres with `ru.yandex.qatools.embed.postgresql.Command#PgCtl` command?

**Comment by smecsia** [comment]
@evrastil Ok. I'll take a look what can be done a bit later.

**Comment by smecsia** [comment]
@evrastil I guess we can close the ticket, since your PR is already in the released version.

**Comment by evrastil** [comment]
@smecsia yes, thank you
