### ISSUE TITLE
Port not passed through when using a custom config

### ISSUE THREAD

**Issue by sideshowcoder** [yandex-qatools/postgresql-embedded#32]
When I'm configuring the embedded postgres to run with a Custom configuration the port option does not seem to passed through to the underlying Postgres process, I see the following output when running 

```
$ ps ax 
...
4571   ??  S      0:00.02 /private/var/folders/z3/f3xjjsr12ks22t16mtm29q_w0000gn/T/postgresql-embed-eed63e85-74b2-4511-a804-37f36aab3e02/pgsql/bin/postgres -D /var/folders/z3/f3xjjsr12ks22t16mtm29q_w0000gn/T/postgresql-embed-eed63e85-74b2-4511-a804-37f36aab3e02/db-content-f67979d1-0e6c-4b2b-94b4-15234acbf760 -h 127.0.0.1
```

So only the host and data directory are passed to the postgres process

This is with the configuration as the following, and supposably port 4711, I also checked and the database is actually running on the default port 5432.

```java
final PostgresStarter<PostgresExecutable, PostgresProcess> runtime = PostgresStarter.getDefaultInstance();
final AbstractPostgresConfig.Net network = new AbstractPostgresConfig.Net("127.0.0.1", 4711);
final AbstractPostgresConfig.Storage storage = new AbstractPostgresConfig.Storage("db");
final AbstractPostgresConfig.Credentials credentials = new AbstractPostgresConfig.Credentials("user", "password");
final AbstractPostgresConfig.Timeout timeout = new AbstractPostgresConfig.Timeout();
final PostgresConfig config = new PostgresConfig(V9_4, network, storage, timeout, credentials);
PostgresExecutable exec = runtime.prepare(config);
process = exec.start();

 System.out.println("Running Postgres...");
Thread.sleep(10000000);
```

This was tested on MacOSX with version 1.13

**Comment by smecsia** [comment]
The issue was due to a strange difference between pg_ctl for Postgres 9.4 and Postgres 9.5. The newer one understands multiple `-o` command line arguments, when 9.4 does not.
Anyway the issue must be fixed by #33 . I'll publish the newer release today.

**Comment by smecsia** [comment]
@sideshowcoder Did you have a chance to test with 1.14?

**Comment by smecsia** [comment]
I'm closing this one, since there's no answer. Feel free to reopen if it's still actual.
