### ISSUE TITLE
Debug message pg_ctl: too many command-line arguments (first is "start")

### ISSUE THREAD

**Issue by vzx** [yandex-qatools/postgresql-embedded#34]
I'm not sure if this is actually an issue or not, but it does look a bit worrying. When `PostgresProcess.stop()` is called, I see the following in the log:

```
DEBUG r.y.q.e.p.e.LogWatchStreamProcessor - pg_ctl: too many command-line arguments (first is "start")

DEBUG r.y.q.e.p.e.LogWatchStreamProcessor - Try "pg_ctl --help" for more information.
```

Here is a simple snippet that could reproduce it for me:

```java
public class PostgresEmbeddedTester {
    private static final Logger LOG = LoggerFactory.getLogger(PostgresEmbeddedTester.class);

    public static void main(String[] args) throws Exception {
        LOG.info("Starting postgres");
        PostgresProcess process = PostgresStarter.getDefaultInstance().prepare(new PostgresConfig(Version.Main.PRODUCTION,
                "test-db")).start();

        LOG.info("Stopping postgres");
        process.stop();
    }
}
```

(With `logback-classic` in the classpath with default config, which has `DEBUG` enabled).

This is using `postgres-embedded` version 1.14 on a 64-bit Ubuntu Mate 15.10.

**Comment by vzx** [comment]
I actually stumbled upon something strange: if I don't call `stop()` at all, the shutdown hook will property stop (or kill) the postgres process, but if I do call `stop()`, it will fail to stop the process for some reason, and the shutdown hook will not attempt to try it again (which means the postgres process keeps running).

So there is definitely a bug with `stop()` I would say.

**Comment by smecsia** [comment]
@vzx Thanks for the report. I'll investigate this a bit later.
