### ISSUE TITLE
Fails to start when run as user without HOME directory

### ISSUE THREAD

**Issue by mfelsche** [yandex-qatools/postgresql-embedded#39]
starting embedded postgres (_Version:_ 9.4.1208) with a user without home directory like this:
(the important thing it to set `.artifactStorePath(new SubdirTempDir())` 
as it failed trying to use the `new UserHome()` with `PostgresStarter.getDefaultInstance()`)

``` scala
val pgConfig: PostgresConfig = new PostgresConfig(
      Version.V9_5_0,
      pgHost, Network.getFreeServerPort, "test")
    pgConfig.getAdditionalInitDbParams.addAll(util.Arrays.asList("--auth=trust", "--auth-host=trust", "--auth-local=trust"))
    val logWatch: LogWatchStreamProcessor = new LogWatchStreamProcessor("started", new util.HashSet[String](singletonList("failed")), new LoggingOutputStreamProcessor(Logger.getLogger("postgres"), Level.ALL))
    val runTimeConfig = new RuntimeConfigBuilder()
    .defaults(Command.Postgres)
    .artifactStore(new ArtifactStoreBuilder()
      .defaults(Command.Postgres)
      .download(
        new DownloadConfigBuilder()
          .defaultsForCommand(Command.Postgres)
          .artifactStorePath(new SubdirTempDir()).build()
      )
    ).processOutput(new ProcessOutput(logWatch, logWatch, logWatch))
    .build()

    PostgresStarter.getInstance(runTimeConfig).prepare(pgConfig).start()
```

It still wants to create `$HOME/.embedpostgresql` when calling initdb here: https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/main/java/ru/yandex/qatools/embed/postgresql/PostgresProcess.java#L70 which does not honor the given `IRuntimeConfig`. Why does ot need to create its own in this method?

**Comment by smecsia** [comment]
@mfelsche I would say it does not. But for now this is a limitation of embedprocess library, where we must provide just a single binary to be extracted and then executed. 
But I agree, this looks like a bug and should be fixed somehow. I'll investigate this later.
Btw if you have an idea of how to fix this, feel free to send a PR.

**Comment by mfelsche** [comment]
:+1:
