### ISSUE TITLE
Privileges on windows

### ISSUE THREAD

**Issue by danpeter** [yandex-qatools/postgresql-embedded#5]
Hi, trying to run this on windows, get the following error:

"Execution of PostgreSQL by a user with administrative permissions is not permitted.
The server must be started under an unprivileged user ID to prevent possible system security compromises.  See the documentation for more information on how to properly start the server."

Is there some configuration to specify another user to start as, or to disable this in postgres?

**Comment by smecsia** [comment]
@danpeter Thank you for sharing this. I haven't tested it under windows actually, since I'm using linux. I will investigate this issue later this week and let you know if it's possible to work around this.

**Comment by isaachazan** [comment]
A problem that is somewhat related to this and maybe there is a solution, our build are generated by teamcity server that as root and i can't really change it.
Is there a way/setting to tell the PostgresStarter to run the postgres instance with a different user than the one that ran the program?

**Comment by smecsia** [comment]
This library is based on [flapdoodle-embed-process](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process), which does not support this. 
I would recommend you to reconfigure your build environment. Running builds as system user is definitely not very good way to do this.

**Comment by smecsia** [comment]
I believe this issue is solved by #29
