### ISSUE TITLE
Problem with encoding on WIndows 10

### ISSUE THREAD

**Issue by tdziurko** [yandex-qatools/postgresql-embedded#52]
Hello

We are using this library to write tests and on OS X it works like a charm. But when we try to execute tests on WIn10 x64 we are getting following errors:

`ERROR: character with byte sequence 0xc5 0xbc in encoding "UTF8" has no equivalent in encoding "WIN12`

I am suspecting that somehow default encoding for Win is different than default encoding for OS X and that is causing this issue, but I can't find a working approach to fix it,

**Comment by smecsia** [comment]
@tdziurko Unfortunately, I don't have the possibility to test the library under Windows for now. If you find the way to workaround this issue, please feel free to open a PR.

**Comment by melezov** [comment]
PR which resolves this is available #61

**Comment by smecsia** [comment]
@tdziurko New release contains the fix. So, I'm closing this issue. Feel free to reopen if it does not work.
