### ISSUE TITLE
Never be able to stop PostgresProcess properly

### ISSUE THREAD

**Issue by Zingoer** [yandex-qatools/postgresql-embedded#56]
I always got the following warning:
```
sDec 23, 2016 2:29:59 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
INFO: trying to stop postgresql
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess sendStopToPostgresqlInstance
INFO: Cleaning up after the embedded process (removing /tmp/postgresql-embed-65eef1e1-5328-48dd-bef4-950c6dbe0984)...
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
WARNING: could not stop postgresql with command, try next
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
WARNING: could not stop postgresql, try next
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
WARNING: could not stop postgresql, try next
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
WARNING: could not stop postgresql the second time, try one last thing
Dec 23, 2016 2:30:00 PM ru.yandex.qatools.embed.postgresql.PostgresProcess deleteTempFiles
WARNING: Could not delete temp db dir: /tmp/postgresql-embed-65eef1e1-5328-48dd-bef4-950c6dbe0984/db-content-8a126cef-37fa-4003-84e7-70bc90134def
```
I know that if I want to delete the /tmp/postgresql-embed..., I need to sudo previledge. I'm not sure if that's the reason lead the stop problem. If so, how should I change the tmp dir to where I have general privilege to delete? If not, what's the possible reason that make the process not be able to stop?

**Comment by smecsia** [comment]
@Zingoer you should not need the sudo privilege to delete temporary files. Which OS are you using?

**Comment by okthatsneat** [comment]
+1 same output; i'm logged in as user, not super user. deleting that file via rm -rf is no problem.

**Comment by bobdenardd** [comment]
Same issue on windows 10 as well

**Comment by Zingoer** [comment]
@smecsia I'm using Linux Ubuntu 16.4.
How could I modify the path to download the postgres? like "/root/.embedpostgresql/postgresql-9.5.0-1-linux-x64-binaries.tar.gz DONE". I want to put in another dir.
As well, the previous console log only appears when I try to run junit in eclipse. If I use gradle clean test, it didn't show these information.

**Comment by smecsia** [comment]
@Zingoer 
> How could I modify the path to download the postgres?

Unfortunately you cannot. There're issues for that (#39, #55).

> /root/.embedpostgresql/postgresql-9.5.0-1-linux-x64-binaries.tar.gz DONE

Are you using root for your tests? This is a weird scenario. I would not recommend it. Besides, postgres is known to not start under root (see readme).
As for the output. Can you debug the [shutdown code](https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/main/java/ru/yandex/qatools/embed/postgresql/PostgresProcess.java#L111) to see what's happening?

@bobdenardd It would be very cool if you could research that behaviour more deeply. I don't have Windows to test library properly.

**Comment by Zingoer** [comment]
@smecsia 
I'm using docker container to run the tests. I noticed the root issue today so I'm trying to figure out how to switch to another user to run the tests inside docker container. 
I will debug the shutdown code, thank you!

**Comment by smecsia** [comment]
@Zingoer  FYI: I've just released v1.17 of the lib with the #39 and #55 fixes.

**Comment by Zingoer** [comment]
@smecsia Awesome! Thank you!

**Comment by bobdenardd** [comment]
@smecsia I had to address the problem because of the windows environment. Here is what I did:

I wrote a CustomPostgresProcess which intends to override the stopInternal method of the PostgresProcess. Here is the new method content:

```java
@Override
protected void stopInternal() {
    synchronized (this) {
            if (!isStopped()) {
                setStopped(true);
                if (!sendStopToPostgresqlInstanceCustom()) {
                    // Here sleep for 2500 millis in order to give enough time to windows to actually stop the process
                    safeSleep(2500);
                    if (!sendKillToProcess()) {
                        if (!sendTermToProcess()) {
                            if (!tryKillToProcess()) {
                                logger.warn("could not stop postgresql the second time, try one last thing");
                            }
                        }
                    }
                }
            }
            // Making sure the process got released by windows
            safeSleep(2500);
            // Now actually deleting all the files, the file handles being released
            deleteTempFiles();
            final IDirectory tempDir = ((PostgresArtifactStore) this.runtimeConfig.getArtifactStore()).getTempDir();
            if (tempDir != null && tempDir.asFile() != null) {
                System.out.println(format("Cleaning up after the embedded process (removing %s)...", tempDir.asFile().getAbsolutePath()));;
                forceDelete(tempDir.asFile());
            }
        }
    }
}
```

This is a quick and dirty workaround, but I can confirm it works and that the trouble was caused by windows not having enough time to kill the process which was still having handles on the files inteded to get deleted.

Since the stopped field and the executeShutdownPostgres method are private I had to use some reflexion to make them accessible (kind of crappy).

Hope that helps, best regards

**Comment by smecsia** [comment]
@bobdenardd I've just pushed the commit, which is trying to shutdown postgres in more proper way. Can you test it locally, please?

**Comment by bobdenardd** [comment]
@smecsia Yes I can confirm it works locally on a win 10 and a win 7 machine. Thanks a bunch :)
