### ISSUE TITLE
Gitlab build: postmaster.pid does not exist

### ISSUE THREAD

**Issue by adihubba** [yandex-qatools/postgresql-embedded#63]
Hi,
everything works fine when i start the database on my local client. But when i used the CI feature from Gitlab i get the following error:
[error.txt](https://github.com/yandex-qatools/postgresql-embedded/files/752676/error.txt)

Any suggestions?

**Comment by smecsia** [comment]
@adihubba it looks like it could not start Postgres process. Can you try to use more verbose logging in your tests?

**Comment by adihubba** [comment]
Ok, i see that gitlab launches the process as root user. I guess i have to check the Gitlab CI config, if i can start the build/test as normal user....
[Log2.txt](https://github.com/yandex-qatools/postgresql-embedded/files/757561/Log2.txt)
