### ISSUE TITLE
slow startup

### ISSUE THREAD

**Issue by hbrackmann** [yandex-qatools/postgresql-embedded#65]
currently the startup time is about 50 seconds which is too long.
Most time is spend for file coppies.

System:
-Windows
-ssd
-i7

i have implemented a low level optimisation for write files in de.flapdoodle.embed.process.io.file.Files
Although this is alreday faster (20 secounds) it is still too slow.

Maybe there are other ways to improve the performance e.g. 
-only replace the postgress data folder
-filter not required files like docus or tools
etc
```
static final ThreadPoolExecutor syncThread;
static {
	syncThread = new ThreadPoolExecutor(20,20,1,TimeUnit.MINUTES,new ArrayBlockingQueue<Runnable>(20));
	syncThread.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy());
}
public static void write(InputStream in, File output) throws IOException {
	ByteArrayOutputStream out = new ByteArrayOutputStream(65536*10);
	ByteStreams.copy(in,out);
	FileChannel c = FileChannel.open(output.toPath(), StandardOpenOption.WRITE, StandardOpenOption.CREATE,StandardOpenOption.READ);
	final byte[] array = out.toByteArray();
	MappedByteBuffer b = c.map(FileChannel.MapMode.READ_WRITE, 0, array.length);
	b.put(array);
	syncThread.submit(()->{
			b.force();
			try {
				c.close();
			} catch (IOException e) {
				throw new RuntimeException(e);
			}
	});
}
```

**Comment by smecsia** [comment]
> currently the startup time is about 50 seconds which is too long.
Oh wow. That's looking too bad. On Linux I get 10 seconds of full startup without any optimizations. 

You may consider not extracting the files every time. This is currently not supported, but you can use your own `ArtifactStore` implementation (which can be instantiated by your own `ArtifactStoreBuilder` and configured using `artifactStore` method of `RuntimeConfigBuilder`). Try to use the preextracted directory of PostgreSQL and see if it boosts your startup.

**Comment by DmitryGlotov** [comment]
@smecsia it would be great if you provide these `ArtifactStore`, `ArtifactStoreBuilder` implementations

**Comment by smecsia** [comment]
@hbrackmann @DmitryGlotov I've added the requested implementations. [Here](https://github.com/yandex-qatools/postgresql-embedded#how-to-use-avoid-archive-extraction-on-every-run) you can find an example of how to configure the cached pg directory.
