### ISSUE TITLE
Too many logs in the output

### ISSUE THREAD

**Issue by Mike-Now** [yandex-qatools/postgresql-embedded#66]
Way too many logs are shown in the output for two operations: prepare and start.
The first "Extract ..." log appears during the prepare phase and two additional during the start phase.

The code that outputs the logs:

    PostgresStarter<PostgresExecutable, PostgresProcess> runtime =  PostgresStarter.getDefaultInstance();
    final PostgresConfig config = new PostgresConfig( V9_4,
        new AbstractPostgresConfig.Net( HOST, PORT ),
        new AbstractPostgresConfig.Storage( DB_NAME ),
        new AbstractPostgresConfig.Timeout(),
        new AbstractPostgresConfig.Credentials( USERNAME, PASSWORD ) );
    config.getAdditionalInitDbParams()
          .addAll( asList( "-E", "SQL_ASCII", "--locale=C", "--lc-collate=C", "--lc-ctype=C" ) );

    PostgresExecutable exec = runtime.prepare( config );
    process = exec.start();

The logs:

> Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz START
> ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz DONE
> Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz START
> ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz DONE
> 2017-02-25_00:09:03.783 INFO  d.f.embed.process.runtime.Executable - start AbstractPostgresConfig{storage=Storage{dbDir=/tmp/postgresql-embed-269d8860-7423-4065-94f1-1c142a0e002d/db-content-2e25256c-0f8b-4bf7-8e68-e8ea611e2578, dbName='db', isTmpDir=true}, network=Net{host='localhost', port=54542}, timeout=Timeout{startupTimeout=15000}, credentials=Credentials{username='user', password='password'}, args=[], additionalInitDbParams=[-E, SQL_ASCII, --locale=C, --lc-collate=C, --lc-ctype=C]}
> Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz START
> ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Extract /home/mnowotnik/.embedpostgresql/postgresql-9.4.10-1-linux-x64-binaries.tar.gz DONE
> 2017-02-25_00:09:04.456 INFO  d.f.embed.process.runtime.Executable - start AbstractPostgresConfig{storage=Storage{dbDir=/tmp/postgresql-embed-269d8860-7423-4065-94f1-1c142a0e002d/db-content-2e25256c-0f8b-4bf7-8e68-e8ea611e2578, dbName='db', isTmpDir=true}, network=Net{host='localhost', port=54542}, timeout=Timeout{startupTimeout=15000}, credentials=Credentials{username='user', password='password'}, args=[db], additionalInitDbParams=[]}
> 2017-02-25_00:09:07.457 INFO  d.f.embed.process.runtime.Executable - start AbstractPostgresConfig{storage=Storage{dbDir=/tmp/postgresql-embed-269d8860-7423-4065-94f1-1c142a0e002d/db-content-2e25256c-0f8b-4bf7-8e68-e8ea611e2578, dbName='db', isTmpDir=true}, network=Net{host='localhost', port=54542}, timeout=Timeout{startupTimeout=15000}, credentials=Credentials{username='user', password='password'}, args=[], additionalInitDbParams=[-E, SQL_ASCII, --locale=C, --lc-collate=C, --lc-ctype=C]}

**Comment by athimel** [comment]
+1

I think an quick fix could be to use the Slf4j log appender instead of console appender in the DownloadConfigBuilder (not sure about the terms). And just comment the line `System.out.print('.')`

**Comment by smecsia** [comment]
@Mike-Now  The problem now is that there's no unified logging approach in the library. And this approach has been inherited from `embed-process` library.
But you can configure logging properties using your `log4j.properties` and `logging.properties` files. And also you can change `progressListener` to your own ProgressListener implementation ([example](https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/test/java/ru/yandex/qatools/embed/postgresql/TestPostgresStarter.java#L51)). 

To configure the java.util.logging logger you will need to add something like the following code:

```java
LogManager.getLogManager().readConfiguration(getClass().getClassLoader().getResourceAsStream("logging.properties"));
```

In your `log4j.properties` you can specify something like:
```
# suppress inspection "UnusedProperty" for whole file
log4j.rootLogger=DEBUG, stdout

# disable logging for postgresql-embedded
log4j.logger.ru.yandex.qatools.embed=OFF
log4j.logger.de.flapdoodle.embed=OFF

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
log4j.throwableRenderer=org.apache.log4j.EnhancedThrowableRenderer
```
And in `logging.properties`:
```
# Logging
handlers = java.util.logging.ConsoleHandler
.level = INFO

ru.yandex.qatools.embed.level=OFF
de.flapdoodle.embed.level=OFF
```

This will turn off all the logging produced by the library.

**Comment by smecsia** [comment]
@athimel @Mike-Now I've changed all loggers to use `slf4j`, so you can now easily configure the required severity using `slf4j` configuration ([link](https://github.com/yandex-qatools/postgresql-embedded#how-to-configure-logging))

**Comment by athimel** [comment]
@smecsia : Thanks a lot, sounds great !
