### ISSUE TITLE
PostgresProcess.stopInternal raises false alarm

### ISSUE THREAD

**Issue by rolandrscheel** [yandex-qatools/postgresql-embedded#67]
if (!waitUntilProcessHasStopped(5000)) {
                logger.severe("Postgres has not been stopped within 10s! Something's wrong!");
            }

will always issue a severe log entry, when the process actually has been successfully terminated, as waitUntilProcessHasStopped returns false when the process has stopped.

**Comment by smecsia** [comment]
@rolandrscheel omg, thank you! What a mess...
