### ISSUE TITLE
Hardcoding of download URL needs to be grained on architecture level

### ISSUE THREAD

**Issue by melezov** [yandex-qatools/postgresql-embedded#68]
Latest download for 9.6.2 is `9.6.2-2` for Windows x64, but `9.6.2-1` for others.

**Comment by smecsia** [comment]
@melezov Thanks for the ticket. Not sure what `9.6.2-2` is, but all the archives are available for download using `9.6.2-1`. That is proven by the builds of the PR bumping the version to `9.6.2`.

**Comment by melezov** [comment]
Hey @smecsia, while `9.6.2-1` may seem to work, `9.6.2-2` wasn't published without a reason, as it completely changes all compiled binaries. I'd still opt for adding fine-granularity to future-proof this.

**Comment by melezov** [comment]
Other non `-1` downloads:

    Resolved actual URL for version 9.2 @ windows-x64: https://get.enterprisedb.com/postgresql/postgresql-9.2.20-2-windows-x64-binaries.zip
    Resolved actual URL for version 9.3 @ windows: https://get.enterprisedb.com/postgresql/postgresql-9.3.16-2-windows-binaries.zip
    Resolved actual URL for version 9.4 @ windows: https://get.enterprisedb.com/postgresql/postgresql-9.4.11-2-windows-binaries.zip
    Resolved actual URL for version 9.5 @ windows: https://get.enterprisedb.com/postgresql/postgresql-9.5.6-2-windows-binaries.zip
    Resolved actual URL for version 9.6 @ windows: https://get.enterprisedb.com/postgresql/postgresql-9.6.2-2-windows-binaries.zip

**Comment by smecsia** [comment]
@melezov I actually didn't catch the reason why these files are required...
 Anyway you can always use your own version implementation. Something like: 
```java
new PostgresConfig(
        () -> (IS_OS_WINDOWS) ? "9.6.2-2" : "9.6.2-1",
        new Net("localhost", findFreePort()),
        new Storage("test"),
        new Timeout(),
        new Credentials("user", "password")
);
```

**Comment by smecsia** [comment]
Closing due to no updates.
