### ISSUE TITLE
Problem with finding postgres.exe in cached dir under Windows

### ISSUE THREAD

**Issue by artpass** [yandex-qatools/postgresql-embedded#72]
Hi!

Method extractFileSet() can't match exe file name  with pattern as pattern slash is "/" while in filename it's "\\".
So, the process can't start. Evidently, there's no such problem in *nix systems.

Best regards,
artpass

**Comment by tdziurko** [comment]
This do not resolve the problem, still pattern matcher trying to find executable `postgres` file under Windows uses `\` instead of `/`and as a result fails without starting a database.

**Comment by smecsia** [comment]
@tdziurko I tested it under Windows 10 and it worked. Please make sure you're using the latest versin.
