### ISSUE TITLE
Failed to stop postgres by pg_ctl!

### ISSUE THREAD

**Issue by hoomb** [yandex-qatools/postgresql-embedded#80]
I'm using this code to start Embedded Postgresql

```java
@Component
class EmbeddedPostqreSql {

    private EmbeddedPostgres postgres
    private DataSource dataSource

    @Value('${spring.datasource.dbname}')
    private String dbname

    @Value('${spring.datasource.username}')
    private String username

    @Value('${spring.datasource.password}')
    private String password

    @Bean
    DataSource dataSource() {
        if (null == postgres) {
            startDatabase()
        }

        if (null == dataSource) {
            final PostgresConfig config = postgres.getConfig().get()
            final String jdbcUrl = String.format("jdbc:postgresql://%s:%s/%s",
                    config.net().host(),
                    config.net().port(),
                    config.storage().dbName()
            )

            dataSource = new DriverManagerDataSource(jdbcUrl, username, password)
        }

        return dataSource
    }

    synchronized void startDatabase() {
        if (null == postgres) {
            try {
                System.out.println("Starting Embedded PostqreSQL")
                Path embeddedPostgresCachedRuntimeConfig = Paths.get(System.getProperty("java.io.tmpdir") + "/cached.embedded.postgres")
                if (!Files.exists(embeddedPostgresCachedRuntimeConfig)) {
                    Files.createDirectory(embeddedPostgresCachedRuntimeConfig)
                }

                postgres = new EmbeddedPostgres()
                postgres.start(cachedRuntimeConfig(embeddedPostgresCachedRuntimeConfig),
                        "localhost", 5432,
                        dbname, username, password,
                        Collections.emptyList())

                System.out.println("PostqreSQL started")
            } catch (IOException e) {
                e.printStackTrace()
            }
        }
    }

    synchronized void stopDatabase() {
        dataSource.connection.close()
        postgres.stop()
    }
}
```

But getting these Exceptions after completing the tests:

> 2017-05-10 10:47:22.003  INFO 59145 --- [       Thread-2] r.y.q.embed.postgresql.PostgresProcess   : trying to stop postgresql
> 2017-05-10 10:47:22.324  WARN 59145 --- [       Thread-2] r.y.q.embed.postgresql.PostgresProcess   : Failed to stop postgres by pg_ctl!
> 
> java.lang.RuntimeException: Failed to initialize the executable
> 	at ru.yandex.qatools.embed.postgresql.PostgresStarter.newExecutable(PostgresStarter.java:70) ~[postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresStarter.newExecutable(PostgresStarter.java:24) ~[postgresql-embedded-2.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59) ~[de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49) ~[de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.runCmd(PostgresProcess.java:123) [postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.runCmd(PostgresProcess.java:81) [postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.shutdownPostgres(PostgresProcess.java:136) [postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.sendStopToPostgresqlInstance(PostgresProcess.java:176) [postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.stopInternal(PostgresProcess.java:149) [postgresql-embedded-2.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170) [de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:73) [de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90) [de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
> Caused by: java.lang.reflect.InvocationTargetException: null
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_60]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_60]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_60]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_60]
> 	at ru.yandex.qatools.embed.postgresql.PostgresStarter.newExecutable(PostgresStarter.java:68) ~[postgresql-embedded-2.1.jar:na]
> 	... 12 common frames omitted
> Caused by: java.lang.IllegalStateException: Shutdown in progress
> 	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66) ~[na:1.8.0_60]
> 	at java.lang.Runtime.addShutdownHook(Runtime.java:211) ~[na:1.8.0_60]
> 	at de.flapdoodle.embed.process.runtime.ProcessControl.addShutdownHook(ProcessControl.java:246) ~[de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at de.flapdoodle.embed.process.runtime.Executable.<init>(Executable.java:58) [de.flapdoodle.embed.process-2.0.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.AbstractPGExecutable.<init>(AbstractPGExecutable.java:13) ~[postgresql-embedded-2.1.jar:na]
> 	at ru.yandex.qatools.embed.postgresql.PgCtlExecutable.<init>(PgCtlExecutable.java:18) ~[postgresql-embedded-2.1.jar:na]
> 	... 17 common frames omitted
> 
> 
> 2017-05-10 10:47:22.343  INFO 59145 --- [       Thread-2] d.f.e.process.runtime.ProcessControl     : execSuccess: true [kill, 59159]
> 

EDIT: Using latest Version 2.1 on MacOS

How can I solve the Shutdown Problem?

**Comment by smecsia** [comment]
@hoomb at which moment are you calling `stopDatabase` method?

**Comment by hoomb** [comment]
@smecsia on `cleanupClass` Method:

```java
    def cleanupClass() {
        embeddedPostqreSql.stopDatabase()
    }
```

But even removing the stopDatabase line shows the Exception.

**Comment by smecsia** [comment]
Actually I believe you can safely ignore those messages. They are releated to the race condition between the spring context shutting down and the application lifecycle. 
I've pushed some fix though ( #82  ). Can you please test it and say if it helps?

**Comment by hoomb** [comment]
Thank you for quick fixing the issue. I confirm that it works.

**Comment by hoomb** [comment]
I must open this issue as your provided fix just suppresses the error message and not really fix the issue causing it.
For me is using EmbeddedPostgresql 2.1 in tests is not possible as the Postgresql Process cannot be terminated gracefully and the concurrent tests will compete with each other and cause to all tests to fail as the port is already in use.

**Comment by smecsia** [comment]
Hmm. I'll try to debug this soon. For now you can use random ports in your tests (just as in the tests of this library)

**Comment by Woworks** [comment]
Hi,
I'm having the same issue and don't know even how to workaround it. Is there any news on it?
Thanks!

**Comment by jorgecara** [comment]
Same problem remains with version 2.2.

**Comment by smecsia** [comment]
Hey guys, I've been on vacation for the last month. Now I'm back and ready to take a look at this. I'll try to reproduce in the following couple of days.
From what I can see now, it might be related to #26, so disabling "daemon process" might help. Can you please test the following runtime configuration?

```java
        return new RuntimeConfigBuilder()
                .defaults(Command.Postgres)
                .daemonProcess(false)  // this is the difference from the default configuration
                .artifactStore(new PostgresArtifactStoreBuilder()
                        .defaults(Command.Postgres)
                        .download(new PostgresDownloadConfigBuilder()
                                .defaultsForCommand(Command.Postgres)
                                .build()))
                .build();

```

**Comment by jorgecara** [comment]
I just tried and error remains.

Also if I disable daemon process I have to explicitly invoke postgres.stop(). Otherwise the embedded-postgres will remain running even after my application was stopped.

**Comment by Woworks** [comment]
I tried also and it didn't help either.
