### ISSUE TITLE
Extract file set once

### ISSUE THREAD

**Issue by t9t** [yandex-qatools/postgresql-embedded#89]
I was quite surprised to see multiple entries of `Extract <tar.gz file> START` in my log output and thought the entire distribution was extracted multiple times, indicating some bug. But after some inspection, it seems like only one particular files is extracted each time.

However, `de.flapdoodle.embed.process.extract.AbstractExtractor#extract` allows to extract multiple files at once.

It would be an optimization to only extract the full file set once, rather than extracting each one individually when they're needed (especially since, as far I know, tar archives can only be read sequentially, you can't just seek to the position of the file you want and only read that). I understand that sometimes some binaries are not needed, but even just to start an instance, 3 binaries are extracted and used (and because `stop` is called in a shutdown hook, usually 4 binaries are used in a typical case)..

I looked at the code a bit, and it would seem it's quite possible to create a `FileSet` based on `ru.yandex.qatools.embed.postgresql.Command` and extract them during `prepare()`, but the code changes are a bit too deep for me to grasp fully unfortunately, so I can't provide a PR at this time.

**Comment by smecsia** [comment]
@t9t Please take a look at [this section](https://github.com/yandex-qatools/postgresql-embedded#how-to-avoid-archive-extraction-on-every-run) of the readme. The extraction itself happens at once for the entire archive. It was a specific of `embed-process` library to extract the archive for every binary. But the way described in readme will help you to boost the process.

**Comment by t9t** [comment]
My apologies, @smecsia. I thought I had made certain that I was using the latest version when testing it, but as it turns out I was using the latest version of 1.x, not 2.2. You are right, of course; when I upgraded to 2.2, it only extracts one and is much faster as a result.
